# Generated by Django 2.2.5 on 2021-03-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210328_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фотография'),
        ),
    ]
