# Generated by Django 2.2.5 on 2021-03-28 11:25

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210328_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_picture_path, verbose_name='Фотография'),
        ),
    ]
