# Generated by Django 2.2.5 on 2021-03-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32, verbose_name='login')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Адрес эл. почты')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль')),
            ],
        ),
    ]
